language: c

before_install:
 - sudo apt-get install -qq python-docutils libhiredis-dev libglib2.0-dev

before_script:
  - apt-get source -q varnish
  - cd varnish*
  - ./configure
  - make
  - cd ..
  - ./autogen.sh
  - cd varnish*; varnishdir="$PWD"; cd ..; ./configure --with-varnish="$varnishdir" VMODDIR=`pwd`
  - make

script:
  - make check

